site_name: Pensamientos
site_author: Danyiel Colin
repo_name: DanEscher98/Thoughts
repo_url: https://github.com/DanEscher98/Thoughts
copyright: Copyright &copy; 2020 - 2023 Danyiel Colin
site_description: >-
     Pensamientos e ideas peregrinas

theme:
  name: material
  font:
    text: Libre Baskerville
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash

extra:
  generator: false

markdown_extensions:
  - codehilite
  - tables
  - fenced_code
  - def_list
  - smarty
  - sane_lists
  - attr_list
  - md_in_html
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - search
    #- section-index
  - literate-nav:
      nav_file: SUMMARY.md
